### ISSUE TITLE
Set starting features and roadmap

### ISSUE THREAD

**Issue by fjaguero** [mozillahispano/meteo-webapp#1]
We need a roadmap **to start creating the issues and assigning them**.

It will be a good idea to have a launch meeting but I think that having an etherpad is great to work async.

We can discuss the initial roadmap here but I want to propose to have the documentation in this [etherpad](https://mozhispano.etherpad.mozilla.org/132).

I will be pushing this to get everyone on the same page and start ASAP.

**Comment by iampbernardo** [comment]
I think we will start with an Etherpad. Too many people and time. Meetings just when necessary. Right?

**Comment by fjaguero** [comment]
Since we have other priorities right now, I'm closing this.
